urls.py
from django.contrib import admin
from django.urls import path
from house_arrangements.views import Index, List, Update, Create, Detail, People, Houses, Spots


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name="index"),
    path('houses/', List.as_view(), name="house_list"),
    path('houses/create/', Create.as_view(), name="house_create"),
    path('houses/<int:pk>/', Detail.as_view(), name="house_detail"),
    path('houses/<int:pk>/update', Update.as_view(), name="house_update"),
    path('api/people/', People.as_view(), name="people_api"),
    path('api/spots/', Spots.as_view(), name="spots_api"),
    path('api/houses/', Houses.as_view(), name="houses_api")
]

house_arrangements/models.py
from django.db import models
from django.forms import inlineformset_factory
from django.urls import reverse
from django.core.exceptions import ValidationError

def validate_between_ones(value):
    if value > 1 or value < -1:
        raise ValidationError(f'{value} is not between 1 and -1')

class House(models.Model):
    name = models.CharField(max_length=200)
    cats = models.BooleanField(null=True, default=None)
    dogs = models.BooleanField(null=True, default=None)
    noise = models.FloatField(validators=[validate_between_ones], null=True, default=None)
    early_up = models.FloatField(validators=[validate_between_ones], null=True, default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('house_detail', args=[str(self.id)])

class Spot(models.Model):
    SPOT_TYPES = (
        ('bed', 'Bed'),
        ('floor', 'Floor'),
        ('couch', 'Couch')
    )
    spot_type = models.CharField(max_length=200, choices=SPOT_TYPES)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    house = models.ForeignKey('House', on_delete=models.CASCADE)

SpotFormSet = inlineformset_factory(
    House,
    Spot,
    fields=("spot_type", "name", "description", "quantity"))

class Person(models.Model):
    name = models.CharField(max_length=200)
    spot = models.ForeignKey('Spot', on_delete=models.SET_NULL, null=True, default=None)
    cats = models.FloatField(validators=[validate_between_ones], null=True, default=None)
    dogs = models.FloatField(validators=[validate_between_ones], null=True, default=None)
    noise = models.FloatField(validators=[validate_between_ones], null=True, default=None)
    early_up = models.FloatField(validators=[validate_between_ones], null=True, default=None)
    bed = models.FloatField(validators=[validate_between_ones], null=True, default=None)

    def __str__(self):
        return self.name

    def set_spot(self, spot_id):
        if spot_id == -1:
            self.spot = None
        else:
            spot = Spot.objects.get(id=spot_id)
            if spot.person_set.count() + 1 > spot.quantity:
                raise ValidationError(f'Spot {spot.id} is full')
            else:
                self.spot = spot
        self.save()

house_arrangements/views.py
from django.views.generic import View, TemplateView, ListView, UpdateView, DetailView, CreateView
from django.views.generic.list import MultipleObjectMixin
from django.http import HttpResponse, JsonResponse, FileResponse
from django.core import serializers
from django.core.exceptions import ValidationError
from django.contrib.staticfiles import finders

from .models import House, Person, Spot, SpotFormSet

class HouseMixin:
    model = House
    fields = ["name"]
    def form_valid(self, form):
        self.object = form.save()
        spots = SpotFormSet(self.request.POST, instance=self.object)
        if spots.is_valid():
            spots.save()
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["spots"] = SpotFormSet(instance=self.object if hasattr(self, 'object') else None)
        return context
    def get_template_names(self):
        return ["%s%s.html" % (self.model._meta.model_name, self.template_name_suffix)]

class List(HouseMixin, ListView):
    pass

class Create(HouseMixin, CreateView):
    pass

class Detail(HouseMixin, DetailView):
    pass

class Update(HouseMixin, UpdateView):
    pass

class Index(View):
    def get(self, req):
        return FileResponse(open(finders.find('html/index.html'),'rb'))
    def post(self, req):
        person_id = int(req.POST.get('person'))
        spot_id = int(req.POST.get('spot'))
        try:
            Person.objects.get(id=person_id).set_spot(spot_id)
            return HttpResponse('')
        except ValidationError:
            return HttpResponse(
                f'Tried to move {person_id} to spot {spot_id}', status=403)

class ExposeModelAsJSONView(MultipleObjectMixin, View):
    def get(self, request, *args, **kwargs):
        return JsonResponse(serializers.serialize('json', self.get_queryset()), safe=False)

class People(ExposeModelAsJSONView):
    model = Person
class Spots(ExposeModelAsJSONView):
    model = Spot
class Houses(ExposeModelAsJSONView):
    model = House

house_arrangements/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}House Arrangements{% endblock %}</title>
  {% load static %}
  {% block stylesheets %}
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock stylesheets %}
</head>
<body>
  <nav>
    {% block navigation %}
      <ul>
        <li>
          <a href="{% url 'index' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'house_list' %}">Houses</a>
        </li>
      </ul>
    {% endblock %}
  </nav>
  {% block content %}{% endblock %}
</body>

{% block scripts %}{% endblock %}
{% block root_scripts %}
  {% load static %}
  <script src="https://unpkg.com/packery@2/dist/packery.pkgd.min.js"></script>
  <script src="https://unpkg.com/draggabilly@2/dist/draggabilly.pkgd.min.js"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.min.js'></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script src="{% static '/js/lib.js' %}" charset="utf-8"></script>
  <script src="{% static '/js/index.js' %}" charset="utf-8"></script>
{% endblock root_scripts %}
</html>

house_arrangements/templates/house_create.html
{% extends 'base.html' %}

{% block content %}
<h1>New House</h1>
<form action="/houses/create/" method="post">
  {% csrf_token %}
  {{ form }}
  {{ spots }}
  <input type="submit" value="OK">
</form>
{% endblock content %}

house_arrangements/templates/house_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.name }}</h1>
<ul>
{% for spot in object.spot_set.all %}
  <li>{{spot.spot_type}}</li>
{% endfor %}
</ul>

{% endblock content %}

house_arrangements/templates/house_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Edit House</h1>
<form action="{% url 'house_update' object.id %}" method="post">
  {% csrf_token %}
  {{ form }}
  {{ spots }}
  <input type="submit" value="OK">
</form>
{% endblock content %}

house_arrangements/templates/house_list.html
{% extends 'base.html' %}

{% block content %}
<ul>
{% for house in object_list %}
  <li><a href="{% url 'house_detail' house.id %}">{{house.name}}</a></li>
{% endfor %}
</ul>
{% endblock content %}

house_arrangements/templates/index.html
{% extends 'base.html' %}
{% load range %}
{% block content %}

<h1>House Arrangements</h1>
<div id="work-holder">
  <div id="house-none" class="people grid-item stamp">
    <h2>Unhoused Persons</h2>
    <div id="people-container" class="people-container container"></div>
  </div>
</div>

{% endblock %}